"""
jobs_data.py - Curated Government Jobs & Exams Dataset
Covers Tier 1 (10th/12th basic) to Tier 5 (UPSC/Group A elite) across all sectors.
All criteria follow official Government of India / State notifications.
"""

GOVT_JOBS = [
    # ==========================================
    # TIER 1: 10th & 12th Pass (Basic / Entry Level)
    # ==========================================
    {
        "id": "india-post-gds",
        "title": "India Post Gramin Dak Sevak (GDS / BPM / ABPM)",
        "department": "Department of Posts, Ministry of Communications",
        "tier": 1,
        "tier_label": "10th Pass (Entry Level)",
        "sector": "Postal",
        "vacancies": 44228,
        "status": "open",
        "app_start_date": "2026-09-01",
        "app_end_date": "2026-09-28",
        "exam_date": "Direct Merit Based (No Written Exam)",
        "min_age": 18,
        "max_age_general": 40,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "10th",
        "allowed_education": ["10th", "12th", "iti", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Class 10th Mathematics and English studied as compulsory/elective", "Basic Computer Training (60 days)", "Cycling knowledge"],
        "pay_level": "Level 1 TRCA",
        "salary_range": "₹12,000 - ₹29,380",
        "in_hand_salary": "₹16,500 - ₹22,000/mo",
        "selection_stages": ["Automatic Merit List based on 10th Class Board Marks", "Document Verification", "Medical Examination"],
        "apply_url": "https://indiapostgdsonline.gov.in",
        "notification_pdf_url": "https://indiapostgdsonline.gov.in/pdf/Notification_GDS.pdf",
        "official_portal": "https://indiapostgdsonline.gov.in",
        "description": "Recruitment of Branch Postmaster (BPM) and Assistant Branch Postmaster (ABPM) across all postal circles in India. No entrance test required; 10th board marks determine selection.",
        "syllabus_highlights": ["No exam! 100% selection based on Class 10 marks percentage normalized across boards."],
        "preparation_tips": "Ensure name on 10th certificate matches Aadhaar card exactly. Obtain basic 60-day computer certificate."
    },
    {
        "id": "ssc-mts-havaldar",
        "title": "SSC Multi-Tasking Staff (MTS) & Havaldar (CBIC/CBN)",
        "department": "Staff Selection Commission (SSC)",
        "tier": 1,
        "tier_label": "10th Pass (Entry Level)",
        "sector": "SSC",
        "vacancies": 9583,
        "status": "closing_soon",
        "app_start_date": "2026-08-20",
        "app_end_date": "2026-09-18",
        "exam_date": "November 2026",
        "min_age": 18,
        "max_age_general": 25,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "10th",
        "allowed_education": ["10th", "12th", "iti", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,  # Required only for Havaldar posts
        "physical_standards": {
            "note": "Physical test only for Havaldar post (MTS has no physical test)",
            "min_height_male": 157.5,
            "min_height_female": 152.0,
            "chest_male": "76 cm unexpanded (5 cm expansion)",
            "running": "Walking 1600m in 15 min (Male) / 1000m in 20 min (Female)"
        },
        "special_skills": [],
        "pay_level": "Pay Level 1 (7th CPC)",
        "salary_range": "₹18,000 - ₹56,900",
        "in_hand_salary": "₹28,500 - ₹33,000/mo",
        "selection_stages": ["CBT Session 1 (Maths & Reasoning - Qualifying)", "CBT Session 2 (General Awareness & English - Merit Ranking)", "PST/PET (Only for Havaldar)"],
        "apply_url": "https://ssc.gov.in",
        "notification_pdf_url": "https://ssc.gov.in/api/annexure/MTS_Notice.pdf",
        "official_portal": "https://ssc.gov.in",
        "description": "General Central Service Group 'C' Non-Gazetted, Non-Ministerial post in various Central Government Ministries, Departments, and Offices across India.",
        "syllabus_highlights": ["Numerical & Mathematical Ability", "Reasoning Ability & Problem Solving", "General Awareness (History, Geography, Polity, Science)", "English Language Comprehension"],
        "preparation_tips": "Focus heavily on General Awareness and English in Session 2, as final ranking is prepared solely on Session 2 marks."
    },
    {
        "id": "rrb-group-d",
        "title": "Railway RRB Group D (Level-1 Track Maintainer / Pointsman / Helper)",
        "department": "Railway Recruitment Boards (RRB), Ministry of Railways",
        "tier": 1,
        "tier_label": "10th / ITI Pass (Entry Level)",
        "sector": "Railways",
        "vacancies": 32450,
        "status": "upcoming",
        "app_start_date": "2026-10-05",
        "app_end_date": "2026-11-05",
        "exam_date": "January - February 2027",
        "min_age": 18,
        "max_age_general": 33,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "10th",
        "allowed_education": ["10th", "12th", "iti", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 160,
            "min_height_female": 150,
            "weight_lift_male": "Carry 35 kg weight for 100 meters in 2 minutes without putting down",
            "weight_lift_female": "Carry 20 kg weight for 100 meters in 2 minutes",
            "running": "Run 1000m in 4 min 15 sec (Male) / 1000m in 5 min 40 sec (Female)"
        },
        "special_skills": ["10th pass OR ITI from NCVT/SCVT or equivalent"],
        "pay_level": "Pay Level 1 (7th CPC)",
        "salary_range": "₹18,000 - ₹56,900",
        "in_hand_salary": "₹26,000 - ₹31,000/mo + Railway Free Pass",
        "selection_stages": ["Computer Based Test (CBT - 100 Marks)", "Physical Efficiency Test (PET)", "Document Verification & Medical (A2/A3/B1/B2/C1 Standards)"],
        "apply_url": "https://www.rrbapply.gov.in",
        "notification_pdf_url": "https://www.rrbapply.gov.in/notifications/CEN_GroupD.pdf",
        "official_portal": "https://indianrailways.gov.in",
        "description": "Massive pan-India recruitment for Level-1 railway operations staff including Track Maintainer Gr IV, Pointsman, Electrical/Mechanical Helpers across all 17 railway zones.",
        "syllabus_highlights": ["General Science (10th standard Physics, Chemistry, Biology - 25 Qs)", "Mathematics (25 Qs)", "General Intelligence & Reasoning (30 Qs)", "General Awareness & Current Affairs (20 Qs)"],
        "preparation_tips": "NCERT Class 9th and 10th science textbooks are the single most important resource for cracking RRB Group D."
    },
    {
        "id": "state-police-constable-up",
        "title": "UP Police Constable (Civil Police & PAC)",
        "department": "Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB)",
        "tier": 1,
        "tier_label": "12th Pass (Entry Level)",
        "sector": "Police",
        "vacancies": 60244,
        "status": "open",
        "app_start_date": "2026-08-25",
        "app_end_date": "2026-09-30",
        "exam_date": "December 2026",
        "min_age": 18,
        "max_age_general": 25,
        "age_relaxation": {"OBC": 5, "SC": 5, "ST": 5, "PwD": 0, "EWS": 0, "ExSM": 3},
        "education_level": "12th",
        "allowed_education": ["12th", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India (Reservation benefits for UP Domicile)",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 168.0,  # 160 for ST
            "min_height_female": 152.0,  # 147 for ST
            "chest_male": "79 cm unexpanded (84 cm expanded)",
            "running": "4.8 km run in 25 min (Male) / 2.4 km run in 14 min (Female)",
            "weight_female": "Minimum 40 kg"
        },
        "special_skills": ["DOEACC/NIELIT 'O' Level certificate preferred (gives tie-breaker weightage)"],
        "pay_level": "Pay Level 3 (7th CPC)",
        "salary_range": "₹21,700 - ₹69,100",
        "in_hand_salary": "₹34,000 - ₹38,000/mo",
        "selection_stages": ["OMR Written Exam (300 Marks, 150 Qs, Negative 0.5)", "Document Verification & Physical Standard Test (PST)", "Physical Efficiency Test (PET - Running)"],
        "apply_url": "https://uppbpb.gov.in",
        "notification_pdf_url": "https://uppbpb.gov.in/Constable_Notification.pdf",
        "official_portal": "https://uppbpb.gov.in",
        "description": "Largest state police recruitment in India. Selected candidates serve as Civil Police Constables and Provincial Armed Constabulary (PAC) personnel across Uttar Pradesh.",
        "syllabus_highlights": ["General Knowledge (38 Qs)", "General Hindi (37 Qs)", "Numerical and Mental Ability (38 Qs)", "Mental Aptitude, I.Q. and Reasoning Ability (37 Qs)"],
        "preparation_tips": "Practice daily Hindi grammar and speed running 5km in 24 minutes in morning hours."
    },
    {
        "id": "delhi-police-constable",
        "title": "Delhi Police Executive Constable (Male & Female)",
        "department": "Staff Selection Commission & Delhi Police",
        "tier": 1,
        "tier_label": "12th Pass (Entry Level)",
        "sector": "Police",
        "vacancies": 7547,
        "status": "upcoming",
        "app_start_date": "2026-10-15",
        "app_end_date": "2026-11-15",
        "exam_date": "January 2027",
        "min_age": 18,
        "max_age_general": 25,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 0, "EWS": 0, "ExSM": 3},
        "education_level": "12th",
        "allowed_education": ["12th", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 170.0,
            "min_height_female": 157.0,
            "chest_male": "81-85 cm (5 cm expansion)",
            "running": "1600m in 6 min (Male) / 1600m in 8 min (Female)",
            "long_jump": "14 feet (Male) / 10 feet (Female)",
            "high_jump": "3'9\" (Male) / 3'0\" (Female)"
        },
        "special_skills": ["Valid Driving License (LMV - Car/Motorcycle) mandatory for Male candidates as on PET date"],
        "pay_level": "Pay Level 3 (7th CPC)",
        "salary_range": "₹21,700 - ₹69,100",
        "in_hand_salary": "₹38,000 - ₹43,000/mo (High X-City HRA & Ration Allowance)",
        "selection_stages": ["Computer Based Examination (100 Marks)", "Physical Endurance & Measurement Test (PE&MT)", "Medical Examination"],
        "apply_url": "https://ssc.gov.in",
        "notification_pdf_url": "https://ssc.gov.in/delhipolice.pdf",
        "official_portal": "https://delhipolice.gov.in",
        "description": "Prestigious capital city police executive post offering central government allowances, accommodation in NCR, and direct promotional hierarchy.",
        "syllabus_highlights": ["General Knowledge / Current Affairs (50 Qs)", "Reasoning (25 Qs)", "Numerical Ability (15 Qs)", "Computer Fundamentals (MS Word, Excel, Internet - 10 Qs)"],
        "preparation_tips": "Score at least 40+ out of 50 in General Knowledge and ensure your LMV driving license is ready well before PET."
    },
    {
        "id": "cisf-constable-tradesman",
        "title": "CISF Constable / Tradesman (Cook, Cobbler, Barber, Washerman)",
        "department": "Central Industrial Security Force (CISF), MHA",
        "tier": 1,
        "tier_label": "10th / ITI Pass (Entry Level)",
        "sector": "Defense",
        "vacancies": 1150,
        "status": "open",
        "app_start_date": "2026-09-05",
        "app_end_date": "2026-10-05",
        "exam_date": "November 2026",
        "min_age": 18,
        "max_age_general": 23,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 0, "EWS": 0, "ExSM": 3},
        "education_level": "10th",
        "allowed_education": ["10th", "12th", "iti", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 170.0,
            "min_height_female": 157.0,
            "chest_male": "80-85 cm",
            "running": "1.6 km in 6 min 30 sec (Male) / 800m in 4 min (Female)"
        },
        "special_skills": ["Skilled in respective trade (Trade test conducted during recruitment)"],
        "pay_level": "Pay Level 3 (7th CPC)",
        "salary_range": "₹21,700 - ₹69,100",
        "in_hand_salary": "₹32,000 - ₹37,000/mo",
        "selection_stages": ["PST / PET & Documentation & Trade Test", "Written Examination (OMR/CBT)", "Detailed Medical Examination (DME)"],
        "apply_url": "https://cisfrectt.cisf.gov.in",
        "notification_pdf_url": "https://cisfrectt.cisf.gov.in/Tradesman_Notification.pdf",
        "official_portal": "https://cisf.gov.in",
        "description": "Central armed police recruitment protecting critical infrastructure like airports, seaports, atomic power plants, and Delhi Metro.",
        "syllabus_highlights": ["General Intelligence & Reasoning", "General Knowledge & Awareness", "Elementary Mathematics", "General English or Hindi"],
        "preparation_tips": "Trade test is qualifying but rigorous. Practical hands-on speed in your chosen trade is essential."
    },
    {
        "id": "state-forest-guard",
        "title": "State Forest Guard & Van Pal Recruitment",
        "department": "State Forest & Wildlife Department",
        "tier": 1,
        "tier_label": "12th Pass (Entry Level)",
        "sector": "State Govt",
        "vacancies": 2640,
        "status": "open",
        "app_start_date": "2026-08-28",
        "app_end_date": "2026-09-29",
        "exam_date": "December 2026",
        "min_age": 18,
        "max_age_general": 28,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 0, "EWS": 0, "ExSM": 3},
        "education_level": "12th",
        "allowed_education": ["12th", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 163.0,
            "min_height_female": 150.0,
            "chest_male": "79-84 cm",
            "walking_endurance": "25 km walking in 4 hours (Male) / 14 km walking in 4 hours (Female)"
        },
        "special_skills": [],
        "pay_level": "Pay Level 2 (7th CPC)",
        "salary_range": "₹19,900 - ₹63,200",
        "in_hand_salary": "₹27,000 - ₹32,000/mo",
        "selection_stages": ["Written Examination (100 Marks)", "Physical Standard & Endurance Test (25km walk)", "Medical & Verification"],
        "apply_url": "https://forestrecruitment.gov.in",
        "notification_pdf_url": "https://forestrecruitment.gov.in/notice_fg.pdf",
        "official_portal": "https://moef.gov.in",
        "description": "Protection of wildlife sanctuaries, national parks, and state forest reserves. Uniformed service with peace of mind in nature.",
        "syllabus_highlights": ["General Science & Ecology", "General Studies & Geography", "Basic Maths", "General Hindi / English"],
        "preparation_tips": "Practice long-distance endurance walking with a light backpack twice a week."
    },
    {
        "id": "high-court-peon-attendant",
        "title": "High Court / District Court Peon, Orderly & Office Attendant",
        "department": "State High Court Judicial Establishment",
        "tier": 1,
        "tier_label": "8th / 10th Pass (Entry Level)",
        "sector": "Judiciary",
        "vacancies": 1820,
        "status": "closing_soon",
        "app_start_date": "2026-08-15",
        "app_end_date": "2026-09-17",
        "exam_date": "October 2026",
        "min_age": 18,
        "max_age_general": 40,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "10th",
        "allowed_education": ["10th", "12th", "iti", "diploma", "graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Must be able to read and write official state language"],
        "pay_level": "Pay Level 1 (7th CPC)",
        "salary_range": "₹18,000 - ₹56,900",
        "in_hand_salary": "₹25,000 - ₹29,000/mo",
        "selection_stages": ["Objective Written Test (100 Marks)", "Interview / Viva-Voce"],
        "apply_url": "https://e-recruitment.highcourt.gov.in",
        "notification_pdf_url": "https://highcourt.gov.in/peon_notice.pdf",
        "official_portal": "https://highcourt.gov.in",
        "description": "Group D judicial staff appointment with secure permanent tenure, uniform allowance, and internal promotional exams to Clerk / Reader.",
        "syllabus_highlights": ["Basic Hindi/Regional Language", "Basic English", "General Knowledge", "Elementary Mathematics"],
        "preparation_tips": "Very simple basic test; accuracy and regional language reading fluency in the interview are key."
    },

    # ==========================================
    # TIER 2: ITI & Diploma (Technical)
    # ==========================================
    {
        "id": "rrb-alp",
        "title": "Railway Assistant Loco Pilot (RRB ALP)",
        "department": "Railway Recruitment Boards (RRB), Ministry of Railways",
        "tier": 2,
        "tier_label": "ITI / Diploma / B.Tech (Technical)",
        "sector": "Railways",
        "vacancies": 18799,
        "status": "open",
        "app_start_date": "2026-08-10",
        "app_end_date": "2026-09-25",
        "exam_date": "November 2026",
        "min_age": 18,
        "max_age_general": 33,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 0, "EWS": 0, "ExSM": 3},
        "education_level": "iti",
        "allowed_education": ["iti", "diploma", "graduate", "post_graduate"],
        "education_streams": ["mechanical", "electrical", "electronics", "automobile", "fitter", "electrician", "diesel_mechanic"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "medical_standard": "A-1 Medical Standard (Strict Vision Test)",
            "vision": "Distant Vision: 6/6, 6/6 without glasses with fogging test; Near Vision: Sn: 0.6, 0.6 without glasses",
            "color_vision": "Must pass Color Vision, Binocular Vision, Field of Vision, and Night Vision tests (Lasik surgery strictly disqualified)"
        },
        "special_skills": ["Matriculation/10th + ITI in specified trade OR 3-year Diploma in Mechanical/Electrical/Electronics/Automobile OR B.Tech in relevant branch"],
        "pay_level": "Pay Level 2 (7th CPC)",
        "salary_range": "₹19,900 - ₹63,200",
        "in_hand_salary": "₹42,000 - ₹55,000/mo (Includes High Running Allowance ₹4.5/km)",
        "selection_stages": ["CBT 1 (Screening Test)", "CBT 2 (Part A - Merit + Part B - Relevant Trade Qualifying)", "Computer-Based Aptitude Test (CBAT - Psycho Test)", "Document Verification & A1 Medical Examination"],
        "apply_url": "https://www.rrbapply.gov.in",
        "notification_pdf_url": "https://www.rrbapply.gov.in/notifications/CEN_ALP.pdf",
        "official_portal": "https://indianrailways.gov.in",
        "description": "Drive passenger and freight electric and diesel locomotives across Indian Railways. High earning potential due to running allowances.",
        "syllabus_highlights": ["CBT 1: Maths, Reasoning, General Science, Current Affairs", "CBT 2 Part A: Basic Science & Engineering, Maths, Reasoning", "Part B: ITI Trade Theory (35% qualifying)", "CBAT: Memory, Depth Perception, Concentration Batteries"],
        "preparation_tips": "Get your eyes tested by an ophthalmologist first to confirm 6/6 uncorrected vision before putting in preparation effort."
    },
    {
        "id": "rrb-technician-iii",
        "title": "RRB Technician Grade III & Grade I Signal",
        "department": "Railway Recruitment Boards (RRB)",
        "tier": 2,
        "tier_label": "10th+ITI / 12th PCM / Diploma (Technical)",
        "sector": "Railways",
        "vacancies": 14298,
        "status": "open",
        "app_start_date": "2026-08-18",
        "app_end_date": "2026-09-22",
        "exam_date": "December 2026",
        "min_age": 18,
        "max_age_general": 33,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "iti",
        "allowed_education": ["12th", "iti", "diploma", "graduate"],
        "education_streams": ["12th_pcm", "iti_any", "mechanical", "electrical", "electronics", "instrumentation"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": {"medical_standard": "B-1 / B-2 Medical Standard (Glasses allowed with conditions)"},
        "special_skills": ["10th + ITI in relevant trade OR 10+2 with Physics and Maths (for S&T posts)"],
        "pay_level": "Pay Level 2 / Pay Level 5",
        "salary_range": "₹19,900 - ₹92,300",
        "in_hand_salary": "₹29,000 - ₹46,000/mo",
        "selection_stages": ["Single Stage CBT (100 Questions, 90 mins)", "Document Verification", "Medical Examination"],
        "apply_url": "https://www.rrbapply.gov.in",
        "notification_pdf_url": "https://www.rrbapply.gov.in/notifications/CEN_Technician.pdf",
        "official_portal": "https://indianrailways.gov.in",
        "description": "Technical maintenance of locomotives, railway coaches, signals, telecom equipment, overhead electrical wires, and tracks across railway workshops.",
        "syllabus_highlights": ["Basic Science and Engineering (40 Qs)", "Mathematics (25 Qs)", "General Intelligence and Reasoning (25 Qs)", "General Awareness (10 Qs)"],
        "preparation_tips": "Basic Science & Engineering (Engineering Drawing, Levers, Work Power Energy, Electricity) holds 40% weightage."
    },
    {
        "id": "ssc-junior-engineer-je",
        "title": "SSC Junior Engineer (JE - Civil / Electrical / Mechanical)",
        "department": "Staff Selection Commission (CPWD, MES, CWC, BRO)",
        "tier": 2,
        "tier_label": "Diploma / B.Tech (Engineering)",
        "sector": "Engineering",
        "vacancies": 1765,
        "status": "upcoming",
        "app_start_date": "2026-10-01",
        "app_end_date": "2026-10-31",
        "exam_date": "January 2027",
        "min_age": 18,
        "max_age_general": 30,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "diploma",
        "allowed_education": ["diploma", "graduate", "post_graduate"],
        "education_streams": ["civil", "electrical", "mechanical"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": {"note": "Border Roads Organisation (BRO) requires minimum physical standards for male candidates only"},
        "special_skills": ["3-year Diploma or Degree in Civil/Electrical/Mechanical Engineering"],
        "pay_level": "Pay Level 6 (7th CPC)",
        "salary_range": "₹35,400 - ₹1,12,400",
        "in_hand_salary": "₹52,000 - ₹62,000/mo",
        "selection_stages": ["Paper 1 (CBT - General Intelligence 50 + General Awareness 50 + Technical Subject 100 Qs)", "Paper 2 (CBT - Technical Domain 100 Qs x 3 marks = 300 Marks)", "Document Verification"],
        "apply_url": "https://ssc.gov.in",
        "notification_pdf_url": "https://ssc.gov.in/JE_Notice.pdf",
        "official_portal": "https://ssc.gov.in",
        "description": "Prestigious engineering positions in Central Public Works Department (CPWD), Military Engineer Services (MES), and Central Water Commission.",
        "syllabus_highlights": ["Domain Engineering: Building Materials, Surveying, RCC, Fluid Mechanics / Electrical Machines, Circuit Law / Thermodynamics", "Reasoning & Non-Tech GK"],
        "preparation_tips": "Revise standard diploma engineering concepts; solve previous 10 years question papers of SSC JE."
    },
    {
        "id": "drdo-ceptam-technician",
        "title": "DRDO CEPTAM Senior Technical Assistant (STA-B) & Technician-A",
        "department": "Defence Research & Development Organisation (DRDO), MoD",
        "tier": 2,
        "tier_label": "B.Sc / Diploma / ITI (Technical)",
        "sector": "Defense",
        "vacancies": 1900,
        "status": "open",
        "app_start_date": "2026-09-02",
        "app_end_date": "2026-09-27",
        "exam_date": "November 2026",
        "min_age": 18,
        "max_age_general": 28,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "diploma",
        "allowed_education": ["iti", "diploma", "graduate"],
        "education_streams": ["mechanical", "electrical", "electronics", "computer_science", "instrumentation", "physics", "chemistry", "mathematics"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Diploma in Engineering/Technology OR B.Sc in recognized Science stream for STA-B; 10th + ITI for Tech-A"],
        "pay_level": "Pay Level 6 (STA-B) / Level 2 (Tech-A)",
        "salary_range": "₹35,400 - ₹1,12,400",
        "in_hand_salary": "₹54,000 - ₹64,000/mo (STA-B)",
        "selection_stages": ["Tier-I (CBT Screening)", "Tier-II (CBT Technical Test for STA-B / Trade Test for Tech-A)", "Document Verification"],
        "apply_url": "https://www.drdo.gov.in/ceptam-notice-board",
        "notification_pdf_url": "https://www.drdo.gov.in/sites/default/files/ceptam_advt.pdf",
        "official_portal": "https://drdo.gov.in",
        "description": "Work in India's premier defense research laboratories developing missiles, fighter aircraft, radar systems, and cutting-edge military hardware.",
        "syllabus_highlights": ["Tier 1: Quantitative Ability, General Intelligence, English, General Awareness, General Science", "Tier 2: Specific Engineering/Science Subject"],
        "preparation_tips": "Strong fundamentals in core branch theory will easily clear Tier-2 which decides final merit."
    },

    # ==========================================
    # TIER 3: Graduate General (Any Degree)
    # ==========================================
    {
        "id": "ssc-cgl",
        "title": "SSC Combined Graduate Level (SSC CGL - Inspector, ASO, Auditor)",
        "department": "Staff Selection Commission (SSC)",
        "tier": 3,
        "tier_label": "Graduate (Any Stream)",
        "sector": "SSC",
        "vacancies": 17727,
        "status": "closing_soon",
        "app_start_date": "2026-08-15",
        "app_end_date": "2026-09-17",
        "exam_date": "October - November 2026",
        "min_age": 18,
        "max_age_general": 30,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "note": "Physical test only for Excise Inspector/Examiner/Preventive Officer/CBI. Desk posts (ASO, Auditor, Tax Assistant) have NO physical test.",
            "min_height_male": 157.5,
            "min_height_female": 152.0,
            "chest_male": "81 cm (expanded 86 cm)",
            "running": "Walking 1600m in 15 mins (Male), Cycling 8 km in 30 mins"
        },
        "special_skills": ["Computer Knowledge Test & Data Entry Speed Test (DEST 2000 key depressions in 15 mins) mandatory qualifying"],
        "pay_level": "Pay Level 4 to Level 7 (7th CPC)",
        "salary_range": "₹25,500 - ₹1,42,400",
        "in_hand_salary": "₹45,000 - ₹82,000/mo",
        "selection_stages": ["Tier 1 (CBT - Qualifying)", "Tier 2 (Paper 1: Maths, Reasoning, English, General Awareness + Computer Module + Typing Test)", "Document Verification"],
        "apply_url": "https://ssc.gov.in",
        "notification_pdf_url": "https://ssc.gov.in/api/annexure/Notice_CGL.pdf",
        "official_portal": "https://ssc.gov.in",
        "description": "Most popular graduate exam in India. Recruits Assistant Section Officers (MEA, CSS, IB, Railway Ministry), Income Tax Inspectors, Central Excise Inspectors, and CAG Auditors.",
        "syllabus_highlights": ["Tier 1: 100 Qs (200 Marks) - Maths 25, Reasoning 25, English 25, GK 25", "Tier 2: Mathematical Abilities (30 Qs), Reasoning (30 Qs), English (45 Qs), General Awareness (25 Qs), Computer (20 Qs)"],
        "preparation_tips": "Do not neglect Computer Knowledge and Typing practice, as scoring 350+ in Tier-2 is wasted if you fail the computer cutoff."
    },
    {
        "id": "ibps-po",
        "title": "IBPS Probationary Officer / Management Trainee (IBPS PO)",
        "department": "Institute of Banking Personnel Selection (11 Public Sector Banks)",
        "tier": 3,
        "tier_label": "Graduate (Any Stream)",
        "sector": "Banking",
        "vacancies": 4455,
        "status": "open",
        "app_start_date": "2026-08-22",
        "app_end_date": "2026-09-24",
        "exam_date": "October 2026 (Prelims) / November 2026 (Mains)",
        "min_age": 20,
        "max_age_general": 30,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 5},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Operating and working knowledge in computer systems is mandatory"],
        "pay_level": "Officer Scale-I (JMG Scale I)",
        "salary_range": "₹36,000 - ₹63,840 (Basic)",
        "in_hand_salary": "₹58,000 - ₹68,000/mo + Lease Accommodation & Perks",
        "selection_stages": ["Preliminary Examination (Online 100 Marks)", "Mains Examination (200 Objective + 25 Descriptive)", "Common Interview (100 Marks)"],
        "apply_url": "https://www.ibps.in",
        "notification_pdf_url": "https://www.ibps.in/crp-po-mt-notification/",
        "official_portal": "https://ibps.in",
        "description": "Direct entry to Scale-I Officer cadre across Bank of Baroda, Canara Bank, PNB, Union Bank of India, and other nationalized banks.",
        "syllabus_highlights": ["Prelims: English (30 Qs), Quantitative Aptitude (35 Qs), Reasoning Ability (35 Qs) - Sectional Timers", "Mains: Data Analysis, Reasoning & Computer, General/Economy/Banking Awareness, English, Letter/Essay Writing"],
        "preparation_tips": "Practice puzzles, data interpretation sets, and read daily banking editorial columns for General Awareness."
    },
    {
        "id": "sbi-clerk",
        "title": "SBI Junior Associate (Customer Support & Sales / SBI Clerk)",
        "department": "State Bank of India (SBI)",
        "tier": 3,
        "tier_label": "Graduate (Any Stream)",
        "sector": "Banking",
        "vacancies": 8283,
        "status": "upcoming",
        "app_start_date": "2026-10-10",
        "app_end_date": "2026-11-02",
        "exam_date": "December 2026",
        "min_age": 20,
        "max_age_general": 28,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India (State vacancy quota with Local Language Proficiency)",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Proficiency in specified local language of the applied state"],
        "pay_level": "Clerical Cadre",
        "salary_range": "₹19,900 - ₹47,920",
        "in_hand_salary": "₹36,000 - ₹42,000/mo + Petrol & Newspaper allowance",
        "selection_stages": ["Preliminary Exam (100 Marks)", "Main Exam (200 Marks)", "Local Language Test (Exempt if studied in 10th/12th)"],
        "apply_url": "https://bank.sbi/careers",
        "notification_pdf_url": "https://bank.sbi/careers/documents/SBI_Clerk_Notice.pdf",
        "official_portal": "https://bank.sbi/careers",
        "description": "Join India's largest bank as Junior Associate. Fixed working hours, generous leave policy, and internal fast-track promotion to Officer in 3 years.",
        "syllabus_highlights": ["Prelims: English, Numerical Ability, Reasoning Ability (No sectional cutoffs in SBI!)", "Mains: General/Financial Awareness (50 Qs), General English (40 Qs), Quantitative Aptitude (50 Qs), Reasoning & Computer (50 Qs)"],
        "preparation_tips": "SBI does NOT have sectional cutoff in Prelims! Maximize overall score in your strongest sections."
    },
    {
        "id": "cds-exam",
        "title": "Combined Defence Services (UPSC CDS - IMA, INA, AFA, OTA)",
        "department": "Union Public Service Commission (Army, Navy, Air Force)",
        "tier": 3,
        "tier_label": "Graduate (Any Stream / B.Tech)",
        "sector": "Defense",
        "vacancies": 459,
        "status": "open",
        "app_start_date": "2026-08-20",
        "app_end_date": "2026-09-20",
        "exam_date": "November 2026",
        "min_age": 19,
        "max_age_general": 24,
        "age_relaxation": {"OBC": 0, "SC": 0, "ST": 0, "PwD": 0, "EWS": 0, "ExSM": 0},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 157.5,
            "min_height_female": 152.0,
            "eye_sight": "6/6 without glasses (Navy/Air Force strict); corrective spectacles permitted within limits for Army/OTA",
            "fitness": "Push-ups, sit-ups, chin-ups, 2.4 km run under 10 minutes"
        },
        "special_skills": ["Degree for IMA/OTA; Degree with Physics & Maths at 10+2 OR B.E./B.Tech for Air Force; Engineering Degree for Naval Academy"],
        "pay_level": "Pay Level 10 (Lieutenant / Sub Lieutenant / Flying Officer)",
        "salary_range": "₹56,100 - ₹1,77,500 + MSP ₹15,500",
        "in_hand_salary": "₹95,000 - ₹1,20,000/mo + Officers Mess, Free Healthcare & Rations",
        "selection_stages": ["Written Examination (English, GK, Elementary Maths; OTA has only English + GK)", "Services Selection Board (SSB Interview - 5 Days testing)", "Medical Board"],
        "apply_url": "https://upsconline.nic.in",
        "notification_pdf_url": "https://upsc.gov.in/CDS_Notice.pdf",
        "official_portal": "https://upsc.gov.in",
        "description": "Commissioned Officer entry into Indian Armed Forces. Lead soldiers, fly fighter jets, or command warships with unmatched honor and dignity.",
        "syllabus_highlights": ["English (100 Marks)", "General Knowledge (100 Marks)", "Elementary Mathematics (100 Marks - Not for OTA)"],
        "preparation_tips": "Clear written exam comfortably, but dedicate daily time to current affairs discussion and physical endurance for SSB interview."
    },
    {
        "id": "state-police-sub-inspector",
        "title": "State Police Sub-Inspector (SI / Daroga)",
        "department": "State Police Recruitment Board (UP, MP, Bihar, Rajasthan)",
        "tier": 3,
        "tier_label": "Graduate (Any Stream)",
        "sector": "Police",
        "vacancies": 3840,
        "status": "open",
        "app_start_date": "2026-08-30",
        "app_end_date": "2026-10-02",
        "exam_date": "December 2026",
        "min_age": 21,
        "max_age_general": 28,
        "age_relaxation": {"OBC": 5, "SC": 5, "ST": 5, "PwD": 0, "EWS": 0, "ExSM": 3},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India (Reservation for Home State)",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "min_height_male": 168.0,
            "min_height_female": 152.0,
            "chest_male": "79-84 cm",
            "running": "4.8 km in 28 mins (Male) / 2.4 km in 16 mins (Female)"
        },
        "special_skills": [],
        "pay_level": "Pay Level 6 (7th CPC)",
        "salary_range": "₹35,400 - ₹1,12,400",
        "in_hand_salary": "₹52,000 - ₹62,000/mo + Uniform & Arms Allowance",
        "selection_stages": ["Online Written Exam (400 Marks, 4 Sections)", "Document Verification & Physical Standard Test (PST)", "Physical Efficiency Test (PET - Running)", "Medical Exam"],
        "apply_url": "https://uppbpb.gov.in",
        "notification_pdf_url": "https://uppbpb.gov.in/SI_Notice.pdf",
        "official_portal": "https://uppbpb.gov.in",
        "description": "Station In-Charge / Investigating Officer post with immense authority, field power, and official vehicle.",
        "syllabus_highlights": ["General Hindi (100 Marks)", "Law / Constitution & GK (100 Marks)", "Numerical & Mental Ability (100 Marks)", "Mental Aptitude / IQ / Reasoning (100 Marks)"],
        "preparation_tips": "Must clear 35% sectional cutoff in Mool Vidhi (Basic Law) and Constitution. Read Indian Penal Code and landmark cases."
    },

    # ==========================================
    # TIER 4: Professional & Domain-Specific
    # ==========================================
    {
        "id": "gate-psu-ongc-iocl",
        "title": "GATE PSU Trainee Engineers (ONGC, IOCL, NTPC, BHEL)",
        "department": "Public Sector Undertakings (Maharatna / Navratna PSUs)",
        "tier": 4,
        "tier_label": "B.Tech / B.E. (Engineering)",
        "sector": "PSU",
        "vacancies": 3200,
        "status": "open",
        "app_start_date": "2026-09-01",
        "app_end_date": "2026-10-15",
        "exam_date": "Based on GATE 2026/2027 Score",
        "min_age": 21,
        "max_age_general": 28,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["mechanical", "electrical", "civil", "chemical", "instrumentation", "computer_science"],
        "min_percentage": 60,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Valid GATE Score in relevant engineering paper + Minimum 60% marks in B.Tech/B.E."],
        "pay_level": "E-1 / E-2 Executive Cadre",
        "salary_range": "₹60,000 - ₹1,80,000",
        "in_hand_salary": "₹85,000 - ₹1,30,000/mo (CTC ₹18 to ₹24 Lakhs per annum)",
        "selection_stages": ["GATE Score (85% weightage)", "Personal Interview & Group Task (15% weightage)", "Medical Fitness"],
        "apply_url": "https://ongcindia.com/careers",
        "notification_pdf_url": "https://ongcindia.com/recruitment_gate.pdf",
        "official_portal": "https://ongcindia.com",
        "description": "Highest paying public sector executive engineering jobs in India with world-class facilities, offshore allowances, and township housing.",
        "syllabus_highlights": ["Engineering Mathematics (13 Marks)", "General Aptitude (15 Marks)", "Core Engineering Technical Subjects (72 Marks)"],
        "preparation_tips": "Focus on high-weightage GATE subjects and previous 20 years GATE questions to achieve rank under 300."
    },
    {
        "id": "ctet-teaching",
        "title": "Central Teacher Eligibility Test (CTET - Paper 1 & Paper 2)",
        "department": "Central Board of Secondary Education (CBSE) for KVS / NVS / EMRS",
        "tier": 4,
        "tier_label": "D.El.Ed / B.Ed (Teaching)",
        "sector": "Teaching",
        "vacancies": 85000,
        "status": "closing_soon",
        "app_start_date": "2026-08-16",
        "app_end_date": "2026-09-19",
        "exam_date": "November 2026",
        "min_age": 18,
        "max_age_general": 50,
        "age_relaxation": {"OBC": 0, "SC": 0, "ST": 0, "PwD": 0, "EWS": 0, "ExSM": 0},
        "education_level": "diploma",
        "allowed_education": ["diploma", "graduate", "post_graduate"],
        "education_streams": ["education", "deled", "bed", "btc"],
        "min_percentage": 50,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["D.El.Ed for Primary (Classes I-V) OR B.Ed for Upper Primary (Classes VI-VIII)"],
        "pay_level": "Qualifying Certificate (Applies to PRT Level 6 / TGT Level 7 / PGT Level 8)",
        "salary_range": "₹35,400 - ₹1,51,100",
        "in_hand_salary": "₹48,000 - ₹72,000/mo (when hired in KVS/NVS)",
        "selection_stages": ["Paper-1 (For Classes I-V Primary: 150 Marks)", "Paper-2 (For Classes VI-VIII Upper Primary: 150 Marks)", "Certificate validity: Lifetime"],
        "apply_url": "https://ctet.nic.in",
        "notification_pdf_url": "https://ctet.nic.in/information_bulletin.pdf",
        "official_portal": "https://ctet.nic.in",
        "description": "Mandatory national qualification certificate required to apply for permanent teacher vacancies in Kendriya Vidyalaya (KVS), Navodaya Vidyalaya (NVS), Delhi DSSSB, and Army Schools.",
        "syllabus_highlights": ["Child Development and Pedagogy (30 Qs)", "Language I (30 Qs)", "Language II (30 Qs)", "Mathematics & Environmental Studies (60 Qs) OR Science/Social Studies (60 Qs)"],
        "preparation_tips": "Child Development Pedagogy carries 90 marks directly or indirectly across all sections. Master Piaget, Vygotsky, and Kohlberg theories."
    },
    {
        "id": "aiims-norcet-nursing",
        "title": "AIIMS NORCET Nursing Officer Recruitment",
        "department": "All India Institute of Medical Sciences (AIIMS, New Delhi & 18 AIIMS)",
        "tier": 4,
        "tier_label": "B.Sc Nursing / GNM (Healthcare)",
        "sector": "Healthcare",
        "vacancies": 3550,
        "status": "open",
        "app_start_date": "2026-08-25",
        "app_end_date": "2026-09-26",
        "exam_date": "October 2026",
        "min_age": 18,
        "max_age_general": 30,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "graduate",
        "allowed_education": ["diploma", "graduate"],
        "education_streams": ["nursing", "bsc_nursing", "gnm"],
        "min_percentage": 50,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["B.Sc Nursing OR Diploma in GNM with 2 years experience in 50-bedded hospital; Registered with State/Indian Nursing Council"],
        "pay_level": "Pay Level 7 (7th CPC)",
        "salary_range": "₹44,900 - ₹1,42,400",
        "in_hand_salary": "₹75,000 - ₹88,000/mo (High Nursing Allowance & AIIMS Benefits)",
        "selection_stages": ["NORCET Stage I (Prelims - 100 Qs Screening)", "NORCET Stage II (Mains - 100 Scenario-Based Clinical Qs)", "Document Verification"],
        "apply_url": "https://www.aiimsexams.ac.in",
        "notification_pdf_url": "https://www.aiimsexams.ac.in/pdf/NORCET_Notice.pdf",
        "official_portal": "https://aiimsexams.ac.in",
        "description": "Prestigious permanent healthcare career at AIIMS institutes across New Delhi, Rishikesh, Bhopal, Patna, Jodhpur, Bhubaneswar, and Raipur.",
        "syllabus_highlights": ["Nursing Core: Medical Surgical, Pharmacology, Obstetrics & Gynaecology, Paediatric, Community Health", "General Knowledge & Aptitude (20 Qs)"],
        "preparation_tips": "NORCET Stage II is heavily clinical scenario and image-based. Focus on emergency protocols and drug calculations."
    },
    {
        "id": "judicial-service-civil-judge",
        "title": "State Judicial Services Examination (Civil Judge Junior Division)",
        "department": "High Court & State Public Service Commission",
        "tier": 4,
        "tier_label": "LLB / LLM (Law)",
        "sector": "Judiciary",
        "vacancies": 303,
        "status": "upcoming",
        "app_start_date": "2026-10-12",
        "app_end_date": "2026-11-12",
        "exam_date": "January 2027",
        "min_age": 22,
        "max_age_general": 35,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 3},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["law", "llb", "ba_llb", "bba_llb", "llm"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Bachelor of Laws (LL.B.) degree from recognized university, enrolled as Advocate"],
        "pay_level": "Junior Civil Judge Scale",
        "salary_range": "₹77,840 - ₹1,36,520 (Second National Judicial Pay Commission)",
        "in_hand_salary": "₹1,05,000 - ₹1,25,000/mo + Bungalow, Car & Security",
        "selection_stages": ["Preliminary Exam (Objective Law + GK)", "Mains Written Examination (Subjective Law Papers I, II, III + Language)", "Viva-Voce / Personal Interview"],
        "apply_url": "https://highcourtjudiciary.gov.in",
        "notification_pdf_url": "https://highcourtjudiciary.gov.in/Judicial_Exam.pdf",
        "official_portal": "https://highcourtjudiciary.gov.in",
        "description": "Enter the judicial service directly as a Judge / Magistrate presiding over civil and criminal courtrooms. Extraordinary constitutional authority.",
        "syllabus_highlights": ["Substantive Law: Law of Contracts, Torts, Transfer of Property, Hindu Law, Muslim Law", "Procedure & Evidence: CPC, CrPC, Indian Evidence Act", "Penal, Revenue & Local Laws"],
        "preparation_tips": "Bare Acts must be at your fingertips. Practice answer writing for Mains with citation of leading constitutional judgments."
    },

    # ==========================================
    # TIER 5: Advanced & Elite (Group A / Gazetted)
    # ==========================================
    {
        "id": "upsc-civil-services",
        "title": "UPSC Civil Services Examination (IAS, IPS, IFS, IRS)",
        "department": "Union Public Service Commission (DoPT, Government of India)",
        "tier": 5,
        "tier_label": "Group A Gazetted (Elite)",
        "sector": "UPSC",
        "vacancies": 1105,
        "status": "open",
        "app_start_date": "2026-08-01",
        "app_end_date": "2026-09-30",
        "exam_date": "May 2027 (Prelims)",
        "min_age": 21,
        "max_age_general": 32,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 5},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "note": "Physical test only for IPS and technical police cadres. IAS, IFS, IRS, IAAS have NO physical fitness cutoff.",
            "min_height_male": 165.0,
            "min_height_female": 150.0,
            "chest_male": "84 cm (5 cm expansion)"
        },
        "special_skills": ["Candidates in final year of degree are eligible to appear for Prelims"],
        "pay_level": "Pay Level 10 (Starting) to Pay Level 18 (Cabinet Secretary)",
        "salary_range": "₹56,100 - ₹2,50,000",
        "in_hand_salary": "₹82,000 - ₹1,10,000/mo + Official Residence, Car, Peon & High Authority",
        "selection_stages": ["Civil Services Preliminary Examination (GS 1 + CSAT Qualifying)", "Civil Services Main Examination (9 Subjective Papers - 1750 Marks)", "Personality Test / Interview (275 Marks)"],
        "apply_url": "https://upsconline.nic.in",
        "notification_pdf_url": "https://upsc.gov.in/sites/default/files/Notification_CSE.pdf",
        "official_portal": "https://upsc.gov.in",
        "description": "The mother of all competitive examinations in India. Selected candidates lead districts as District Magistrate (DM/Collector), Superintendents of Police (SP), Diplomats abroad, and Revenue Commissioners.",
        "syllabus_highlights": ["Prelims: GS Paper 1 (Polity, History, Geography, Economy, Science, Environment) + GS Paper 2 (CSAT 33% qualifying)", "Mains: Essay, GS I, GS II, GS III, GS IV (Ethics), Optional Subject (2 Papers), Compulsory Languages"],
        "preparation_tips": "Master NCERTs (Class 6 to 12) for core concepts, read The Hindu or Indian Express daily, and practice daily GS answer writing."
    },
    {
        "id": "rbi-grade-b-officer",
        "title": "Reserve Bank of India Grade 'B' Officer (General)",
        "department": "Reserve Bank of India (RBI)",
        "tier": 5,
        "tier_label": "Group A / Regulatory (Elite)",
        "sector": "Banking",
        "vacancies": 291,
        "status": "closing_soon",
        "app_start_date": "2026-08-20",
        "app_end_date": "2026-09-19",
        "exam_date": "October 2026 (Phase 1) / November 2026 (Phase 2)",
        "min_age": 21,
        "max_age_general": 30,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 5},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 60,  # 50% for SC/ST/PwD
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": None,
        "special_skills": ["Minimum 60% marks (50% for SC/ST/PwD) in Graduation or Post-Graduation. 6 attempts limit for General category."],
        "pay_level": "Officer Grade 'B'",
        "salary_range": "₹55,200 - ₹99,750 (Basic)",
        "in_hand_salary": "₹1,16,000/mo approx + ₹50,000/mo Lease Accommodation in Mumbai/Metros",
        "selection_stages": ["Phase-I Examination (Objective 200 Marks, 120 mins)", "Phase-II Examination (Paper 1: Economic & Social Issues, Paper 2: English Descriptive, Paper 3: Finance & Management)", "Interview (75 Marks)"],
        "apply_url": "https://www.rbi.org.in",
        "notification_pdf_url": "https://opportunities.rbi.org.in/scripts/bs_viewcontent.aspx?Id=GradeB",
        "official_portal": "https://rbi.org.in",
        "description": "Apex central banking role in India. Formulate monetary policy, regulate foreign exchange, and supervise India's commercial banking system.",
        "syllabus_highlights": ["Phase 1: General Awareness (80 Qs!), Reasoning (60 Qs), English (30 Qs), Quantitative Aptitude (30 Qs)", "Phase 2: Economic & Social Issues, Finance & Management, English Writing"],
        "preparation_tips": "General Awareness in Phase 1 is the decider (80 marks). Follow RBI bulletin, PIB releases, and Union Budget thoroughly."
    },
    {
        "id": "state-psc-uppsc-pcs",
        "title": "UPPSC Combined State / Upper Subordinate Services (PCS Exam)",
        "department": "Uttar Pradesh Public Service Commission (UPPSC)",
        "tier": 5,
        "tier_label": "Group A / State Administrative (Elite)",
        "sector": "State Govt",
        "vacancies": 860,
        "status": "open",
        "app_start_date": "2026-08-10",
        "app_end_date": "2026-09-29",
        "exam_date": "December 2026",
        "min_age": 21,
        "max_age_general": 40,
        "age_relaxation": {"OBC": 5, "SC": 5, "ST": 5, "PwD": 15, "EWS": 0, "ExSM": 5},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["any"],
        "min_percentage": 0,
        "state_eligibility": "All-India (Reservation for UP Domicile)",
        "gender_allowed": "all",
        "physical_required": True,
        "physical_standards": {
            "note": "Physical test only for DSP post. SDM, BDO, Treasury Officer have NO physical test.",
            "min_height_male": 165.0,
            "min_height_female": 152.0,
            "chest_male": "84-89 cm"
        },
        "special_skills": [],
        "pay_level": "Pay Level 10 (SDM/DSP: ₹56,100) and Level 7 (₹44,900)",
        "salary_range": "₹44,900 - ₹1,77,500",
        "in_hand_salary": "₹78,000 - ₹95,000/mo + Official Car, Bungalow, Gunner",
        "selection_stages": ["Preliminary Exam (Paper 1 GS + Paper 2 CSAT 33% Qualifying)", "Mains Written Exam (General Hindi + Essay + GS 1 to GS 6 Papers - 1500 Marks)", "Interview (100 Marks)"],
        "apply_url": "https://uppsc.up.nic.in",
        "notification_pdf_url": "https://uppsc.up.nic.in/PCS_Notification.pdf",
        "official_portal": "https://uppsc.up.nic.in",
        "description": "Appoints Sub-Divisional Magistrates (SDM), Deputy Superintendents of Police (Dy. SP), Block Development Officers (BDO), and Commercial Tax Officers across Uttar Pradesh.",
        "syllabus_highlights": ["Prelims: Paper 1 (150 Qs) + CSAT", "Mains: GS 1 to 4 + GS 5 & GS 6 (Dedicated Uttar Pradesh History, Economy, Culture, Polity)"],
        "preparation_tips": "UPPSC eliminated optional subjects and introduced GS Paper 5 & 6 on UP state. Thorough mastery of Uttar Pradesh GK gives massive advantage."
    },
    {
        "id": "upsc-indian-engineering-services",
        "title": "UPSC Engineering Services Examination (ESE / IES)",
        "department": "Union Public Service Commission (Indian Railway Service, CPWD, MES, Telecom)",
        "tier": 5,
        "tier_label": "Group A Gazetted / Engineering (Elite)",
        "sector": "UPSC",
        "vacancies": 410,
        "status": "upcoming",
        "app_start_date": "2026-10-01",
        "app_end_date": "2026-11-04",
        "exam_date": "February 2027",
        "min_age": 21,
        "max_age_general": 30,
        "age_relaxation": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "EWS": 0, "ExSM": 5},
        "education_level": "graduate",
        "allowed_education": ["graduate", "post_graduate"],
        "education_streams": ["civil", "mechanical", "electrical", "electronics", "telecommunication"],
        "min_percentage": 0,
        "state_eligibility": "All-India",
        "gender_allowed": "all",
        "physical_required": False,
        "physical_standards": {"medical_standard": "Executive Engineering Medical Standards"},
        "special_skills": ["Degree in Engineering (Civil/Mechanical/Electrical/Electronics & Telecommunication) from recognized university"],
        "pay_level": "Pay Level 10 (Junior Time Scale)",
        "salary_range": "₹56,100 - ₹1,77,500",
        "in_hand_salary": "₹92,000 - ₹1,12,000/mo + Central Govt Gazetted Rank & Quarters",
        "selection_stages": ["Stage-I: ESE Prelims (Paper 1 GS + Paper 2 Engineering Discipline = 500m)", "Stage-II: ESE Mains (Two Conventional Technical Papers = 600m)", "Stage-III: Personality Test (200m)"],
        "apply_url": "https://upsconline.nic.in",
        "notification_pdf_url": "https://upsc.gov.in/Notification_ESE.pdf",
        "official_portal": "https://upsc.gov.in",
        "description": "The pinnacle of engineering careers in India. Appoints Assistant Executive Engineers who design and manage national infrastructure, power grids, and defense installations.",
        "syllabus_highlights": ["Paper 1: General Studies, Engineering Ethics, Project Management, Environmental Studies, ICT", "Paper 2 & Mains: Comprehensive core branch engineering domain"],
        "preparation_tips": "Practice conventional step-by-step numerical solving for Stage-II; handwriting, presentation, and formula derivations carry high marks."
    }
]

def get_all_jobs():
    """Return all curated government jobs."""
    return GOVT_JOBS

def get_job_by_id(job_id):
    """Fetch single job by ID."""
    for job in GOVT_JOBS:
        if job["id"] == job_id:
            return job
    return None
